// ─── Shared domain types ────────────────────────────────────────────────────
// NOTE: Database types are auto-generated by: supabase gen types typescript
// and live in src/types/database.ts (not committed — run the command to regenerate)

export interface Clinic {
  id: string
  name: string
  cnpj: string | null
  phone: string | null
  email: string | null
  address: string | null
  city: string | null
  state: string | null
  createdAt: string
}

export interface Patient {
  id: string
  clinicId: string
  name: string
  cpf: string | null
  birthDate: string | null
  phone: string | null
  email: string | null
  notes: string | null
  createdAt: string
}

export interface Professional {
  id: string
  clinicId: string
  name: string
  specialty: string | null
  crm: string | null   // CRM / CRO / CREFITO etc.
  phone: string | null
  email: string | null
  active: boolean
  createdAt: string
}

export type AppointmentStatus =
  | 'scheduled'
  | 'confirmed'
  | 'completed'
  | 'cancelled'
  | 'no_show'

export interface Appointment {
  id: string
  clinicId: string
  patientId: string
  professionalId: string
  startsAt: string     // ISO 8601, stored in UTC
  endsAt: string
  status: AppointmentStatus
  notes: string | null
  // Amounts stored in centavos (integer) to avoid float issues
  chargeAmountCents: number | null
  paidAmountCents: number | null
  paidAt: string | null
  createdAt: string
}

// ─── Auth ───────────────────────────────────────────────────────────────────
export type UserRole = 'admin' | 'receptionist' | 'professional'

export interface UserProfile {
  id: string
  clinicId: string
  role: UserRole
  name: string
  email: string
}

// ─── Placeholder — will be replaced by supabase gen types ───────────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any
